pull_request_rules:
  - name: Merge PRs when CI/CD passes and is reviewed
    conditions:
      - '#approved-reviews-by>=1'
      - status-success=build
      - label!=Work in progress ⚠️
      - base=master
    actions:
      merge:
        method: squash
  - name: Merge PRs from dependabot if CI passes
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=build
      - base=master
    actions:
      merge:
        method: squash
  - name: Delete host branch after PR is merged
    conditions:
      - merged
    actions:
      delete_head_branch: {}
