version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'weekly'
    default_reviewers:
      - 'xhudec'
    default_assignees:
      - 'xhudec'
    commit_message:
      prefix: 'chore'
      include_scope: true
