name: Continuous Integration

on: [push, pull_request]

env:
  CI: true
  NODE_VERSION: 12.x

jobs:
  verify:
    runs-on: ubuntu-18.04

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: npm ci

      - name: Validate formatting
        run: npm run prettier:validate

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --maxWorkers=2

      - name: Build
        run: npm run build
